"""users upd

Revision ID: 332126d8e148
Revises: 715f70ec6289
Create Date: 2022-01-11 17:22:29.656580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332126d8e148'
down_revision = '715f70ec6289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_weight', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('user_height', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('purpouse', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'purpouse')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'user_height')
    op.drop_column('user', 'user_weight')
    # ### end Alembic commands ###
