"""commit

Revision ID: 4dfafb6901fb
Revises: 
Create Date: 2021-11-14 00:37:38.940774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dfafb6901fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bd_connector', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bd_connector', 'url')
    # ### end Alembic commands ###
