"""added url for news

Revision ID: 50e46e70a851
Revises: bdbb2becd139
Create Date: 2021-11-04 16:43:21.698737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e46e70a851'
down_revision = 'bdbb2becd139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bd_connector', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bd_connector', 'url')
    # ### end Alembic commands ###
