"""rename model and add COmment model

Revision ID: b8d1a706ffae
Revises: e9265c50cfda
Create Date: 2021-11-22 12:33:55.798009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d1a706ffae'
down_revision = 'e9265c50cfda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bd_food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_food', sa.String(), nullable=False),
    sa.Column('calories', sa.String(), nullable=True),
    sa.Column('joules', sa.String(), nullable=True),
    sa.Column('proteins', sa.String(), nullable=True),
    sa.Column('fats', sa.String(), nullable=True),
    sa.Column('carbohydrates', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_consumption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_cons', sa.Integer(), nullable=False),
    sa.Column('cons_product', sa.String(), nullable=False),
    sa.Column('cons_calories', sa.Float(), nullable=False),
    sa.Column('cons_prots', sa.Float(), nullable=True),
    sa.Column('cons_fats', sa.Float(), nullable=True),
    sa.Column('cons_carbos', sa.Float(), nullable=True),
    sa.Column('cons_weight', sa.Float(), nullable=False),
    sa.Column('cons_day', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.Column('published', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_news_id'), 'comment', ['news_id'], unique=False)
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_news_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    op.drop_table('news')
    op.drop_table('daily_consumption')
    op.drop_table('bd_food')
    # ### end Alembic commands ###
