"""users and news tables

Revision ID: d5759a2477d3
Revises: 332126d8e148
Create Date: 2022-01-14 18:06:51.403518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5759a2477d3'
down_revision = '332126d8e148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_weight', sa.Integer(), nullable=True),
    sa.Column('user_height', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('purpouse', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_data_user_id'), 'personal_data', ['user_id'], unique=False)
    op.drop_column('user', 'user_weight')
    op.drop_column('user', 'user_height')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'purpouse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('purpouse', sa.VARCHAR(length=50), nullable=True))
    op.add_column('user', sa.Column('gender', sa.VARCHAR(length=10), nullable=True))
    op.add_column('user', sa.Column('user_height', sa.INTEGER(), nullable=True))
    op.add_column('user', sa.Column('user_weight', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_personal_data_user_id'), table_name='personal_data')
    op.drop_table('personal_data')
    # ### end Alembic commands ###
